[[services]]
name = "goldenity-pos-api-bridge"
start = "node index.js"
healthcheckPath = "/health"
healthcheckTimeout = 10

  [services.build]
  builder = "nixpacks"

  [services.build.args]
  NIXPACKS_BUILD_CMD = "npm install --omit=dev"

[deploy]
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5
